# Site settings
title: Marc Argent
email: me@marcargent.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Marc Argent and this is my personal website. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcargent.com" # the base hostname & protocol for your site
twitter_username: lurcio
github_username:  lurcio

# Build settings
markdown: kramdown
